# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCommitLinter < Formula
  desc "A command-line tool that enforces consistent Git commit message formats"
  homepage "https://github.com/randilt/git-commit-linter"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/randilt/git-commit-linter/releases/download/v0.3.0/git-commit-linter_Darwin_x86_64.tar.gz"
      sha256 "2e2c9e903f154084ca5eb14004609a2c292d3eec81ca7dcbee0bef55c310bf02"

      def install
        bin.install "git-commit-linter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/randilt/git-commit-linter/releases/download/v0.3.0/git-commit-linter_Darwin_arm64.tar.gz"
      sha256 "09691ef0e37b89670b97ac118218abb6b2bb499e4ac390e8b839af509343f752"

      def install
        bin.install "git-commit-linter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/randilt/git-commit-linter/releases/download/v0.3.0/git-commit-linter_Linux_x86_64.tar.gz"
        sha256 "d2c0458d997c9f00ac2b49759d3a2cfbd66240bc12975c552879b37e53860fcd"

        def install
          bin.install "git-commit-linter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/randilt/git-commit-linter/releases/download/v0.3.0/git-commit-linter_Linux_arm64.tar.gz"
        sha256 "83246ccd515b62ff1e3709d21935389d5447ffd33a7f7047692b6bde21615a96"

        def install
          bin.install "git-commit-linter"
        end
      end
    end
  end

  test do
    system "#{bin}/git-commit-linter --version"
  end
end
