# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCommitLinter < Formula
  desc "A command-line tool that enforces consistent Git commit message formats"
  homepage "https://github.com/randilt/git-commit-linter"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/randilt/git-commit-linter/releases/download/v0.1.0/git-commit-linter_Darwin_x86_64.tar.gz"
      sha256 "805f62ba216148e08398a0a7d2f556682f9b87bdec7c4414587e634809063f9d"

      def install
        bin.install "git-commit-linter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/randilt/git-commit-linter/releases/download/v0.1.0/git-commit-linter_Darwin_arm64.tar.gz"
      sha256 "07247a79d4ae3976475c3d751eb37dc0a02ab8ceb31a808e04d3be7eb3dd823c"

      def install
        bin.install "git-commit-linter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/randilt/git-commit-linter/releases/download/v0.1.0/git-commit-linter_Linux_x86_64.tar.gz"
        sha256 "dea5a5dd1a8f071c09ac2383c7c1ef515043d1ec705550158e9c1e59c175679a"

        def install
          bin.install "git-commit-linter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/randilt/git-commit-linter/releases/download/v0.1.0/git-commit-linter_Linux_arm64.tar.gz"
        sha256 "e85f782027ac6898cf8bf5bb2bb693814d2bec89870b17ec91570d853aa4efbb"

        def install
          bin.install "git-commit-linter"
        end
      end
    end
  end

  test do
    system "#{bin}/git-commit-linter --version"
  end
end
